### ISSUE TITLE
Unicode symbols issue

### ISSUE THREAD

**Issue by tsaunya** [nixme/jazz_hands#2]
When i try to type anything in rails console i got this error

```
Error: incompatible character encodings: ASCII-8BIT and UTF-8
/Users/yanis/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/rb-readline-0.4.2/lib/rbreadline.rb:3138:in `[]='
/Users/yanis/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/rb-readline-0.4.2/lib/rbreadline.rb:3138:in `rl_redisplay'
/Users/yanis/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/rb-readline-0.4.2/lib/rbreadline.rb:3898:in `readline_internal_setup'
/Users/yanis/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/rb-readline-0.4.2/lib/rbreadline.rb:4742:in `readline_internal'
/Users/yanis/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/rb-readline-0.4.2/lib/rbreadline.rb:4765:in `readline'
/Users/yanis/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/rb-readline-0.4.2/lib/readline.rb:40:in `readline'
/Users/yanis/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/pry-0.9.10/lib/pry/pry_instance.rb:600:in `block in readline'
/Users/yanis/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/pry-0.9.10/lib/pry/pry_instance.rb:544:in `handle_read_errors'
/Users/yanis/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/pry-0.9.10/lib/pry/pry_instance.rb:589:in `readline'
/Users/yanis/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/pry-0.9.10/lib/pry/pry_instance.rb:369:in `retrieve_line'
/Users/yanis/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/pry-0.9.10/lib/pry/pry_instance.rb:304:in `block in r'
/Users/yanis/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/pry-0.9.10/lib/pry/pry_instance.rb:301:in `loop'
/Users/yanis/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/pry-0.9.10/lib/pry/pry_instance.rb:301:in `r'
/Users/yanis/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/pry-0.9.10/lib/pry/pry_instance.rb:271:in `re'
/Users/yanis/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/pry-0.9.10/lib/pry/pry_instance.rb:251:in `rep'
/Users/yanis/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/pry-0.9.10/lib/pry/pry_instance.rb:231:in `block (3 levels) in repl'
/Users/yanis/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/pry-0.9.10/lib/pry/pry_instance.rb:230:in `loop'
/Users/yanis/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/pry-0.9.10/lib/pry/pry_instance.rb:230:in `block (2 levels) in repl'
/Users/yanis/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/pry-0.9.10/lib/pry/pry_instance.rb:229:in `catch'
/Users/yanis/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/pry-0.9.10/lib/pry/pry_instance.rb:229:in `block in repl'
/Users/yanis/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/pry-0.9.10/lib/pry/pry_instance.rb:228:in `catch'
/Users/yanis/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/pry-0.9.10/lib/pry/pry_instance.rb:228:in `repl'
/Users/yanis/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/pry-0.9.10/lib/pry/pry_class.rb:154:in `start'
/Users/yanis/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/pry-debugger-0.2.0/lib/pry-debugger/pry_ext.rb:19:in `start'
/Users/yanis/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/railties-3.2.6/lib/rails/commands/console.rb:47:in `start'
/Users/yanis/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/railties-3.2.6/lib/rails/commands/console.rb:8:in `start'
/Users/yanis/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/railties-3.2.6/lib/rails/commands.rb:41:in `<top (required)>'
script/rails:6:in `require'
script/rails:6:in `<main>'
FATAL: Pry failed to get user input using `Readline`.
To fix this you may be able to pass input and output file descriptors to pry directly. e.g.
  Pry.config.input = STDIN
  Pry.config.output = STDOUT
  binding.pry

```

**Comment by nixme** [comment]
This was an issue with rb-readline which doesn't handle Unicode characters well. I released a new version of jazz_hands which detects and uses a plain ASCII character instead. You can now also customize the separator via `Jazz_hands.prompt_separator`. Thanks!
